// <auto-generated />
namespace LTCSDLMayBay.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class goiproc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(goiproc));
        
        string IMigrationMetadata.Id
        {
            get { return "202405281328008_goiproc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
